version: 3

tasks:
  default:
    cmds:
      - task --list

  init:
    desc: Initialize Terraform
    cmds:
      - terraform init

  validate:
    desc: Validate Terraform configuration
    deps: [init]
    cmds:
      - terraform validate

  lint:
    desc: Run pre-commit hooks
    cmds:
      - pre-commit run -a

  tf-docs:
    desc: Generate Terraform documentation
    cmds:
      - terraform-docs markdown . --output-file README.md
